### ISSUE TITLE
No x-overflow on code formatted text (```)

### ISSUE THREAD

**Issue by maxanstey** [jhackshaw/ofnotes#8]
If you create some text in a note and wrap it in ``` for code formatted text the x-overflow is not accessible as it looks like the x-overflow is set to none

Thanks!

**Comment by jhackshaw** [comment]
Thanks for pointing this out! It should be fixed now.

**Comment by maxanstey** [comment]
Great @jhackshaw I can confirm it's working 😁 many thanks!

**Comment by maxanstey** [comment]
Resolved
